### ISSUE TITLE
Feature request: migration path docs from CF provider 

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-cloudfoundry#125]
### What area do you want to see improved?

documentation

### Is your feature request related to a problem? Please describe.

Based on prior tooling availability, I used the CloudFoundry community provider in conjunction with the SAP BTP Terraform provider. I hit some of the rough edges that I think this new provider aims to solve.

I absolutely love that this is being developed and 100% plan to adopt it. However:

* It will be a task to transition my existing CF community provider code
* I don't want to necessarily wait until the entire provider hits v1.0.0 if some of the components are stable 

### Describe the solution you would like

If at all possible, I'd like for this repository to be approached with migration in mind:

* Reference points for which resources map to the community provider if they're not the same name 
* A catalog by resource with their status, noting when they become stable.
* Guidance on dual-operating providers with any relevant information
* A migration guide from the community provider as a prerequisite of a resource becoming "stable". Nothing fancy, more a recommended approach to move from one to the other. I imagine the process will roughly be to import a resource into the new provider, remove the state of the old provider and the old provider code.

### Additional context

I absolutely love this and would like to help test on the journey. My concern is that we are approaching production and introducing a new provider may be risky.

Also, I'd be happy to provide some samples of what we're doing if they make sense to contribute to the migration guide. And I'm happy to contribute to those docs myself.

**Comment by SeanKilleen** [comment]
I just noticed #70 -- this is likely a dupe of that with additional context. Happy to have you just close this or let me know if I should move my thoughts there. I loved @lechnerc77's suggestion of the before/after, and I think my suggestion of the migration path would complement it.

**Comment by vipinvkmenon** [comment]
Hi @SeanKilleen, 
It's great to hear you and appreciate you trying this out :)

As you rightly pointed out, we have this in the pipeline.  We have a certain idea of how we'd like to do this. However, are open to your thoughts as well. Feel free to pen down your ideas in #70.

For now, I shall close this ticket and you can also check into #70 for updates on the same.
