### ISSUE TITLE
[FEATURE] Error Handling during new hana cloud instance creation

### ISSUE THREAD

**Issue by surendrababub** [SAP/terraform-provider-cloudfoundry#126]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

for new instance creation if i dont set generateSystemPassword set to true, i am getting broker error ( See the attached image). 
same for even if any any miss match between memory to CPU.

### Describe the solution you would like

if we pass any wrong values to the parameters it should return relevant error.

### Additional context

![image](https://github.com/SAP/terraform-provider-cloudfoundry/assets/169885265/4fb36769-0034-4e73-a745-5676601044b6)

**Comment by lechnerc77** [comment]
@surendrababub Closed here as topic for BTP provider: https://github.com/SAP/terraform-provider-btp/issues/821
