### ISSUE TITLE
[BUG] Documentation issue for field username

### ISSUE THREAD

**Issue by DanSchlachter** [SAP/terraform-provider-cloudfoundry#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

0.2.0-beta

### What version of the Terraform CLI are you using?

1.7.0

### What CF API version are you using?

3.153.0

### What type of issue are you facing

documentation issue

### Describe the bug

The documentation states that a `username` should be provided, which is not  an accepted value, it should be called `user`.
It's also confusing, as it is `username` for the btp provider, why is the similar field called different across the two providers?

From: https://registry.terraform.io/providers/SAP/cloudfoundry/latest/docs
```
provider "cloudfoundry" {
  api_url  = "https://api.cf.example.com"
  username = "admin"
  password = "admin"
}
```

**Comment by lechnerc77** [comment]
Fixed with https://github.com/SAP/terraform-provider-cloudfoundry/pull/131. Will be available with next release.

**Comment by Dray56** [comment]
We named the attribute user initially as even the existing cf-community provider does it. However, we plan to change the attribute from user to username (even if its a breaking change) as it is more natural and matches the convention of BTP provider as well. Will bring it in a future PR.
