### ISSUE TITLE
[BUG] Regression: Not able to assign space role if user does not have organization_user role

### ISSUE THREAD

**Issue by alxsap** [SAP/terraform-provider-cloudfoundry#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

0.2.1-beta

### What version of the Terraform CLI are you using?

OpenTofu v1.6.2

### What CF API version are you using?

3.166.0

### What type of issue are you facing

bug report

### Describe the bug

It seems the issue https://github.com/SAP/terraform-provider-cloudfoundry/issues/53 is not fixed yet. A fix has been released with https://github.com/SAP/terraform-provider-cloudfoundry/pull/54 but seems not to work as expected:

In my `main.tf` I have:

```hcl
resource "cloudfoundry_space_role" "deploy_users" {
  provider   = cloudfoundry-sap
  for_each   = toset(var.deploy_users)
  space      = cloudfoundry_space.space.id
  username   = each.key
  origin     = "sap.ids"
  type       = "space_developer"
}
```

But without assigning an `org_role` first it (still) fails with:

```log
│ Error: API Error Registering Role
│
│   with cloudfoundry_space_role.deploy_users["sapcontinuousdelivery+cf-deploy-prod-1@sap.com"],
│   on main.tf line 159, in resource "cloudfoundry_space_role" "deploy_users":
│  159: resource "cloudfoundry_space_role" "deploy_users" {
│
│ Could not register Role with user ID  : executing POST request for /v3/roles failed: cfclient error (CF-UnprocessableEntity|10008):
    Users cannot be assigned roles in a space if they do not have a role in that space's organization.
```

### Expected Behavior

Assigning a `space_role`, without assigning an `org_role` first, works without an error.

**Comment by Dray56** [comment]
Hi @alxsap,

Creation of an org role is necessary before a space role. #54 was to make this message as an error more clearer to the user and automatic creation of org roles was not performed as it would lead to unwanted dangling CF resources which can be better managed from the user side with an additional terraform resource. Therefore request you to kindly create  cloudfoundry_org_role resources with type organization_user before assigning them space_developer roles.
