### ISSUE TITLE
[BUG] cf config not used for auth

### ISSUE THREAD

**Issue by Akatuoro** [SAP/terraform-provider-cloudfoundry#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

v1.0.0-rc1

### What version of the Terraform CLI are you using?

1.9.4

### What CF API version are you using?

3.167.0

### What type of issue are you facing

bug report

### Describe the bug

When logged in to the cf cli with existing ~/.cf/config.json, the terraform provider responds with:
```
│ Error: Unable to create CF Client due to missing values
│ 
│   with provider["registry.terraform.io/sap/cloudfoundry"],
│   on provider.tf line 12, in provider "cloudfoundry":
│   12: provider "cloudfoundry" {
│ 
│ Either user/password or client_id/client_secret or access_token must be set with api_url or CF config must exist in path (default ~/.cf/config.json)
```

cf cli version: cf version 8.7.11+b1b4068.2024-07-09

### Expected Behavior

The provider uses the existing cli login (as documented)

### Steps To Reproduce

1. terraform init
2. cf login --sso
3. terraform plan

### Your Terraform Configuration

```hcl
terraform {
  required_providers {
    cloudfoundry = {
      source  = "SAP/cloudfoundry"
      version = "1.0.0-rc1"
    }
  }
}

provider "cloudfoundry" {
  # resolve API URL from environment instance
  api_url = "https://api.cf.us10-001.hana.ondemand.com"
}

resource "cloudfoundry_space" "dev" {
  name = "DEV"
  org  = "<org-id>"
}
```

**Comment by vipinvkmenon** [comment]
Hi @Akatuoro

Can you please try removing the `api_url` from the configuration?

```
provider "cloudfoundry" {}
```

**Comment by Akatuoro** [comment]
Hi @vipinvkmenon
Thanks for the hint, it's working.

I also saw that it's actually documented in the [Authentication.md](https://github.com/SAP/terraform-provider-cloudfoundry/blob/main/Authentication.md#using-cf-cli-configuration). What I checked initially was the [documentation in the provider registry](https://registry.terraform.io/providers/SAP/cloudfoundry/latest/docs) where it simply states that cf cli login would also be used without mention of the configuration needing to be empty.

Imho it would make sense that it works even if the api_url is specified and matches the login.

**Comment by vipinvkmenon** [comment]
Hi Akatuoro,
Great to hear :)

Actually, the issue with that approach is that when using this `cf login` method the `go-cfclient` relies on the Authentication token that is saved in the config. This I believe would be against a specific cf API endpoint that is present in the config, so a different `API` on the provider and the one in the config would not work as the token would not work. 

(The CF CLI wouldn't work either if you authenticate against one API and then switch the API.)
