### ISSUE TITLE
[rl-readme_file-2] README is incomplete. Please check the following sections: Requirements, Contributing

### ISSUE THREAD

**Issue by ihrigb** [SAP/terraform-provider-cloudfoundry#89]
This issue was generated by the SAP Repository Linter. It checks repositories for their compliance with the SAP open source project guidelines. As an SAP employee you can see further details at https://wiki.one.int.sap/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-Readme(rl-readme_file-XX)

**Comment by lechnerc77** [comment]
Closed by #98 

- Prerequisites added to header; content was already correct
- Contribution put into dedicated section
